[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[colors.primary]
background = "#282828"
foreground = "#ffffff"

[window]
opacity = 0.9
padding = { x = 5, y = 5 }
position = {x = 1000, y = 100}

[cursor]
style = {shape = "Beam"}

[keyboard]
bindings = [
{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "L", mods = "Control|Shift", chars = "l" },
]
